import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import {
  MoralisProvider,
  WagmiProvider,
  config,
  QueryClientProvider,
  RainbowKitProvider,
  queryClient,
} from "../constants/imports";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MoralisProvider initializeOnMount={false}>
          <WagmiProvider config={config}>
            <QueryClientProvider client={queryClient}>
              <RainbowKitProvider>{children}</RainbowKitProvider>
            </QueryClientProvider>
          </WagmiProvider>
        </MoralisProvider>
      </body>
    </html>
  );
}
